# Generated by Django 3.1.3 on 2020-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201129_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='square_feet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='rent', max_length=40),
        ),
    ]
