# Generated by Django 3.1.3 on 2020-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20201129_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='red_room',
            new_name='bed_room',
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='rent', max_length=40),
        ),
    ]
